data_source:
  base_url: https://www.ncei.noaa.gov/data/local-climatological-data/access/
  year: 2022
  output: C:/Users/sriva/OneDrive/Documents/Github/Assignment4_BDL/Climate_dataset{year}.html
  local: C:/Users/sriva/OneDrive/Documents/Github/Assignment4_BDL
  max_files: 10
  temp_dir: C:/Users/sriva/OneDrive/Documents/Github/Assignment4_BDL/data
data_process:
  dest_folder: C:/Users/sriva/OneDrive/Documents/Github/Assignment4_BDL/process_data
data_prepare:
  dest_folder: C:/Users/sriva/OneDrive/Documents/Github/Assignment4_BDL/prepare_data
evaluate:
  output: C:/Users/sriva/OneDrive/Documents/Github/Assignment4_BDL/output